function dict_omics = make_dict_omics(metabolome,proteome,transcriptome)


keyvalset_m = {'D-Glucose 6-phosphate','G6P';...
    'D-Fructose 6-phosphate','F6P';...
    'D-Fructose 1,6-bisphosphate','F1,6P';...
    'Glycerone phosphate','DHAP';...
    '3-Phospho-D-glycerate','3PG';...
    '2-Phospho-D-glycerate','2PG';...
    'Phosphoenolpyruvate','PEP';...
    'sn-Glycerol 3-phosphate','G3P';...
    'D-Glucose 1-phosphate','G1P';...
    '(S)-Lactate','Lactate';...
    'L-Alanine','Ala';...
    'L-Glutamate','Glu';...
    'L-Aspartate','Asp';...
    'Citrate','Citrate';...
    'Succinate','Succinate';...
    'Fumarate','Fumarate';...
    'Malate','Malate';...
    'Acetyl-CoA','Acetyl-CoA';...
    'CoA','CoA';...
    'ATP','ATP';...
    'ADP','ADP';...
    'AMP','AMP';...
    'NADH','NADH';...
    'NAD+','NAD+';...
    'NADPH','NADPH';...
    'NADP+','NADP+';...
    'GTP','GTP';...
    'GDP','GDP';...
    'FAD','FAD';...
    'L-Leucine','Leu';...
    'L-Phenylalanine','Phe'};

keyset_m = keyvalset_m(:,1);
valset_m = keyvalset_m(:,2);

assert(all(ismember(keyset_m,metabolome.varname_name)));
[~,idx_m] = ismember(keyset_m,metabolome.varname_name);

dict_m.key = keyset_m;
dict_m.val = valset_m;
dict_m.idx = idx_m;

% valset_p = {'Gpi1','Fbp1','Aldoa','Aldob','Tpi1','Gapdh','Pgk1','Pgam1','Bpgm','Eno1',...
%     'Gpd1','Pgm2',...
%     'Pklr','Pck1','Pcx','Ldha','Pdha1','Pdhb','Dld','Dlat',...
%     'Cs','Aco1','Aco2','Idh1','Idh2','Idh3a','Idh3b','Idh3g',...
%     'Ogdh','Dlst','Sucla2','Suclg1','Suclg2','Sdha','Sdhb','Fh1','Mdh1','Mdh2',...
%     'Acly','Acss2','Fasn'}';
valset_p = {'Gpi1','Fbp1','Pgam1','Bpgm','Eno1',...
    'Gpd1','Pgm2',...
    'Pklr','Pcx','Pck1','Ldha','Gpt',...
    'Cs',...
    'Sdha','Sdhb','Fh1','Mdh1','Mdh2','Glud1'};
% assert(all(ismember(valset_p,proteome.varname_name)));
[~,idx_p] = ismember(valset_p,proteome.varname_name);
keyset_p = valset_p;
dict_p.key = keyset_p';
dict_p.val = valset_p';
dict_p.idx = idx_p';

% valset_t = {'G6pc','Gpi1','Fbp1','Aldoa','Aldob','Tpi1','Gapdh','Pgk1','Pgam1','Bpgm','Eno1',...
%     'Gpd1','Gk','Pgm2','Pygl',...
%     'Pklr','Pck1','Pcx','Ldha','Gpt','Got1','Pdha1','Pdhb','Pdhx','Dld','Dlat',...
%     'Cs','Aco1','Aco2','Idh1','Idh2','Idh3a','Idh3b','Idh3g',...
%     'Ogdh','Dlst','Sucla2','Suclg1','Suclg2','Sdha','Sdhb','Sdhc','Sdhd','Fh1','Mdh1','Mdh2',...
%     'Acly','Acaca','Acss2','Fasn'}';
valset_t = valset_p;
assert(all(ismember(valset_t,transcriptome.varname_name)));
[~,idx_t] = ismember(valset_t,transcriptome.varname_name);
keyset_t = valset_t;
dict_t.key = keyset_t';
dict_t.val = valset_t';
dict_t.idx = idx_t';

dict_omics{1} = dict_m;
dict_omics{2} = dict_p;
dict_omics{3} = dict_t;

end